config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :itineraries, only: [:index, :create, :show] do
    resources :starting_points, only: [:create]
    resources :destinations, only: [:new, :create] do
      resources :time_managements, only: [:create]
    end
    member do
      get 'day_schedule'
    end
    
  end
  
  
  authenticated :user do
    root 'maps#dashboard', as: :authenticated_root
  end

  unauthenticated do
    root 'static_pages#home'
  end

  # Stations data endpoint for JSON
  get 'maps/stations_data', to: 'maps#stations_data'

end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
  belongs_to :user
  has_many :destinations, dependent: :destroy
  has_one :starting_point, dependent: :destroy

  # バリデーション
  validates :title, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_date_after_start_date

  # メソッド: 終了日が開始日より後であることをチェック
  private

  def end_date_after_start_date
    return if start_date.blank? || end_date.blank?

    return unless end_date < start_date

    errors.add(:end_date, 'は開始日より後の日付を選択してください')
  end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  before_action :set_itinerary, only: [:show, :day_schedule]

  def create
    @itinerary = Itinerary.new(itinerary_params)

    if @itinerary.save
      render json: { success: true, itinerary_id: @itinerary.id }
    else
      render json: { success: false, errors: @itinerary.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def day_schedule
    current_day = params[:current_day].to_i
    @visit_date = @itinerary.start_date + (current_day - 1).days
    # 当日の目的地を取得
    @destinations = @itinerary.destinations.order(:arrival_order)
    # 出発地情報
    @starting_point = StartingPoint.find_by(itinerary_id: @itinerary.id)
    # 目的地の駅情報を取得
    @station_data = Station.where(name: @destinations.pluck(:destination))
  end

  private

  def itinerary_params
    params.require(:itinerary).permit(:title, :start_date, :end_date).merge(user_id: current_user.id)
  end

  def set_itinerary
    @itinerary = Itinerary.find(params[:id])
  end
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/views/itineraries/_new.html.erb
<%= form_with(model: itinerary, url: itineraries_path, local: true, id: "itinerary-form") do |form| %>
  <div>
    <%= form.label :title, "タイトル" %>
    <%= form.text_field :title, placeholder: "例: 道南スタンプラリー", class: "itinerary-new-form" %>
  </div>
  <div>
    <%= form.label :start_date, "開始日" %>
    <%= form.date_field :start_date, id: "start_date", class: "itinerary-new-form" %>
  </div>
  <div>
    <%= form.label :end_date, "終了日" %>
    <%= form.date_field :end_date, id: "end_date", class: "itinerary-new-form" %>
  </div>
  <div>
    <%= form.submit "登録する", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/itineraries/day_schedule.html.erb
<!-- ヘッダー -->
  <header class="header">
    <div class="welcome">
      <%= @itinerary.title %> <br>
      <%= @visit_date.strftime('%Y年%m月%d日') %>（<%= params[:current_day] %>日目）
    </div>
    </div>
      <%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: 'logout-button' %>
    </div>
  </header>

<main>
<div class="itinerary-contents">
  <!-- 出発地ブロック -->
  <div class="destination-block time-block departure-block">
    <div class="left-section">   
      <label>出発時間:</label>
      <input type="time" class="departure-time">
    </div>
    <div class="right-destination">
      <label>出発地:</label>
      <input type="text" value="<%= @starting_point&.starting_point %>" readonly>
    </div>
  </div>

  <!-- 移動時間ブロック -->
  <div class="destination-block time-block travel-time-block">
    <div class="left-container">
      <div class="left-section">
        <label>移動時間:</label>
        <input type="time" class="travel-time" 
          value="<%= @destinations.first&.api_travel_time.rjust(5, '0')  %>">
      </div>
    </div>
  </div>


  <!-- 目的地ブロック -->
  <% @destinations.each_with_index do |destination, index| %>
  <% station = @station_data.find { |s| s.name == destination.destination } %>
  <div class="destination-block destination-details-block <%= 'goal-destination' if index == @destinations.size - 1 %>"
       data-destination-id="<%= destination.id %>">
    <div class="left-container time-block">
      <div class="left-section">
        <label>到着予定時間:</label>
        <input type="time" class="arrival-time" readonly>
      </div>
      <% unless index == @destinations.size - 1 %>
        <div class="left-section">
          <label>滞在予定時間:</label>
          <input type="time" class="stay-time" value="00:20">
        </div>
        <div class="left-section">   
          <label>出発予定時間:</label>
          <input type="hidden" name="destinations[<%= index %>][next_departure_time]" class="next-departure-time-hidden">
          <input type="time" class="next-departure-time" readonly>
        </div>
      <% end %>
    </div>

    <div class="right-section">
      <h3>目的地:<%= destination.destination %></h3>
      <p><strong>休館日:</strong></p>
      <ul class="no-bullet">
        <% station.closed_days.each do |day| %>
          <li>
            <%= day.closed_info %>
            (<%= day.start_date.gsub('-', '月') + '日' %> 〜 <%= day.end_date.gsub('-', '月') + '日' %>)
            <% if day.remarks.present? %>
              <br><small>備考: <%= day.remarks %></small>
            <% end %>
          </li>
        <% end %>
      </ul>
      <p><strong>営業時間:</strong></p>
      <ul class="no-bullet">
        <% station.business_hours.each do |hour| %>
          <li>
            <%= "#{hour.opening_time.strftime('%H:%M')} 〜 #{hour.closing_time.strftime('%H:%M')}" %>
            (<%= hour.start_date.gsub('-', '月') + '日' %> 〜 <%= hour.end_date.gsub('-', '月') + '日' %>)
          </li>
        <% end %>
      </ul>
      <p><strong>スタンプ押印時間:</strong></p>
      <p class="stamp-hours"><%= station.stamp_available_hours.map(&:available_hour).join(', ') %></p>
    </div>
  </div>

  <!-- 中間の移動時間ブロック -->
  <% unless index == @destinations.size - 1 %> <!-- 最後の目的地では移動時間を表示しない -->
    <div class="destination-block time-block travel-time-block">
      <div class="left-container">
        <div class="left-section">
          <label>移動時間:</label>
          <input type="time" name="destinations[<%= index + 1 %>][custom_travel_time]" class="travel-time"
                value="<%= @destinations[index + 1].api_travel_time.rjust(5, '0') %>">
        </div>
      </div>
    </div>
  <% end %>
<% end %>


<!-- フッター -->
 <footer class="footer-container">
   <button id="register_time" class="footer-link">しおりを<br>登録する</button>
 </footer>

app/views/itineraries/index.html.erb
<h1>しおり一覧</h1>

<ul>
  <% @itineraries.each do |itinerary| %>
    <li>
      <%= link_to itinerary.title, itinerary_path(itinerary) %>
      （開始日: <%= itinerary.start_date %>, 終了日: <%= itinerary.end_date %>）
    </li>
  <% end %>
</ul>

app/views/itineraries/show.html.erb
<h1><%= @itinerary.title %></h1>

<h2>全体の旅程</h2>
<% @destinations_by_date.each do |date, destinations| %>
  <h3><%= date %> の経路</h3>
  <ul>
    <% destinations.each do |destination| %>
      <li>
        <%= destination.departure %> → <%= destination.destination %>
        （距離: <%= destination.distance %> km, 移動時間: <%= destination.api_travel_time %> 分）
      </li>
    <% end %>
  </ul>
<% end %>